config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'exchanges#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api do
    namespace :v1 do
      resources :exchanges
      resources :stock_quotes, only: [:new, :show, :create, :edit, :update, :index]
      resources :transactions
      resources :sessions, only: [:create, :destroy]
    end
  end

  resources :exchanges do
    resources :stocks, only: [:new, :edit, :index, :show]
  end
  resources :stocks, only: [:destroy, :create, :update]
  resources :stock_quotes, only: [:show, :index]
  resources :transactions

  
end

app/models/exchange.rb
# Exchange Table Schema
#
# id              integer
# name      string(255)
# location  string(255)
# active    boolean(default: true)


class Exchange < ApplicationRecord
  has_many :stocks
  has_many :stock_quotes, through: :stocks
  has_many :transactions, through: :stock_quotes

  # If new exchanges become available and we want to support them,
  # add their names here
  VALID_NAMES = ['NASDAQ', 'NYSE']

  validates :name, inclusion: { in: VALID_NAMES, message: "Exchange must be one of these: #{VALID_NAMES.join(', ')}" }
  validates_uniqueness_of :name
end

app/controllers/api/v1/exchanges_controller.rb
class Api::V1::ExchangesController < Api::V1::BaseController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]

  def index
    @exchanges = Exchange.paginate(page: params[:page], per_page: 100)
  end

  def show
    render :show, status: :ok, location: @exchange
  end

  def new
    @exchange = Exchange.new

    render :new, status: :ok, location: @exchange
  end

  def create
    exchange = Exchange.new(exchange_params)

    if exchange.save
      render :show, status: :ok, location: exchange
    else
      render json: exchange.errors, status: :unprocessable_entity
    end
  end

  def edit
    render :edit, status: :ok, location: @exchange
    end
  end

  def update
    if @exchange.update(exchange_params)
      render :show, status: :ok, location: @exchange
    else
      render json: @exchange.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @exchange.destroy
      render :show, status: :ok, location: '/'
    else
      render json: @exchange.errors, status: :unprocessable_entity
    end
  end

private

  def exchange_params
    params.require(:exchange).permit(:name, :location, :active)
  end

  def set_exchange
    @exchange = Exchange.find(params[:id])
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:show, :edit, :update, :destroy]

  def index
    @exchanges = Exchange.paginate(page: params[:page], per_page: 50)
  end

  def show
    respond_to do |format|
      format.html { render 'show' }
      format.json { render :show, status: :ok, location: @exchange }
    end
  end

  def new
    @exchange = Exchange.new

    respond_to do |format|
      format.html { render 'new' }
      format.json { render :new, status: :ok, location: @exchange }
    end
  end

  def create
    @exchange = Exchange.new(exchange_params)

    respond_to do |format|
      if @exchange.save
        format.html { redirect_to @exchange, notice: 'Exchange was successfully created.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :new, alert: @exchange.errors }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html { render 'edit' }
      format.json { render :edit, status: :ok, location: @exchange }
    end
  end

  def update
    respond_to do |format|
      if @exchange.update(exchange_params)
        format.html { redirect_to @exchange, notice: 'Exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange }
      else
        format.html { render :edit, alert: @exchange.errors }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @exchange.destroy
        format.html { redirect_to exchanges_path, notice: 'Exchange was successfully destroyed.' }
        format.json { render :show, status: :ok, location: exchanges_path }
      else
        format.html { render :show, alert: @exchange.errors }
        format.json { render json: @exchange.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def exchange_params
    params.require(:exchange).permit(:name, :location)
  end

  def set_exchange
    @exchange = Exchange.find(params[:id])
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/views/exchanges/_form.html.erb
<%= form_for(exchange) do |f| %>
  <% if exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

      <ul>
      <% exchange.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
    
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
    
  <div>
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Editing Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to "Show #{@exchange.name}", @exchange %> |
<%= link_to 'Back', exchanges_path %>

app/views/exchanges/index.html.erb
<h1>Exchanges</h1>

<%= will_paginate @exchanges %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @exchanges.each do |exchange| %>
      <tr>
        <td><%= link_to exchange.name, exchange %></td>
        <td><%= link_to 'Edit', edit_exchange_path(exchange) %></td>
        <td><%= link_to 'Destroy', exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange', new_exchange_path %>

app/views/exchanges/new.html.erb
<h1>New Exchange</h1>

<%= render 'form', exchange: @exchange %>

<%= link_to 'Back', exchanges_path %>

app/views/exchanges/show.html.erb
<h1><%= "Exchange: #{@exchange.name}" %></h1>
<h2><%= "Location: #{@exchange.location}" %></h2>
<h2><%= "Active? #{@exchange.active?.to_s.capitalize}" %></h2>
<br>
<h2><%= @exchange.name %>'s Stocks</h2>

<% if @exchange.stocks.count > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Destroy</th>
      </tr>
    </thead>

    <tbody>
      <% @exchange.stocks.each do |stock| %>
        <tr>
          <td><%= link_to stock.name, exchange_stock_path(exchange_id: @exchange.id, id: stock.id
          ) %></td>
          <td><%= link_to 'Edit', edit_exchange_stock_path(exchange_id: @exchange.id, id: stock.id) %></td>
          <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5> None </h5><br>
<% end %>
<br>
<%= link_to "Edit #{@exchange.name}", edit_exchange_path(@exchange) %> |
<%= link_to "Back", exchanges_path %>