config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'exchanges#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api do
    namespace :v1 do
      resources :exchanges
      resources :stock_quotes, only: [:new, :show, :create, :edit, :update, :index]
      resources :transactions
      resources :sessions, only: [:create, :destroy]
    end
  end

  resources :exchanges do
    resources :stocks, only: [:new, :edit, :index, :show]
  end
  resources :stocks, only: [:destroy, :create, :update]
  resources :stock_quotes, only: [:show, :index]
  resources :transactions

  
end

app/models/stock.rb
# Stock Table Schema
#
# id           integer
# name         string(255)
# exchange_id  integer

class Stock < ApplicationRecord
  belongs_to :exchange
  has_many   :stock_quotes
end

app/controllers/api/v1/stocks_controller.rb
class Api::V1::StocksController < Api::V1::BaseController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def index
    @stocks = Stock.paginate(page: params[:page], per_page: 100)
  end

  def show
    render :show, status: :ok, location: @stock
  end

  def new
    @stock = Stock.new

    render :new, status: :ok, location: @stock
  end

  def create
    stock = Stock.new(stock_params)

    if stock.save
      render :show, status: :ok, location: stock
    else
      render json: stock.errors, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @stock.update(stock_params)
      render :show, status: :ok, location: @stock
    else
      render json: @stock.errors, status: :unprocessable_entity
    end
  end

  def destroy
    if @stock.destroy
      render :show, status: :ok, location: exchange_stocks_path(exchange_id: @stock.exchange_id)
    else
      render json: @stock.errors, status: :unprocessable_entity
    end
  end

private

  def stock_params
    params.require(:stock).permit(:name, :location)
  end

  def set_stock
    @stock = Stock.find(params[:id])
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :set_exchange, only: [:index, :new, :show, :edit]

  def index
    @stocks = Stock.paginate(page: params[:page], per_page: 100)
  end

  def show
    respond_to do |format|
      format.html { render 'show' }
      format.json { render :show, status: :ok, location: @stock }
    end
  end

  def new
    @stock = Stock.new
    @exchange = Exchange.find(params[:exchange_id])

    respond_to do |format|
      format.html { render 'new' }
      format.json { render :new, status: :ok, location: @stock }
    end
  end

  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to exchange_stock_url(id: @stock.id, exchange_id: @stock.exchange_id),
                      notice: 'Stock was successfully created.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :new, alert: @stock.errors }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    respond_to do |format|
      format.html { render 'edit' }
      format.json { render :edit, status: :ok, location: @stock }
    end
  end

  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to exchange_stock_url(id: @stock.id, exchange_id: @stock.exchange_id),
                      notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, alert: @stock.errors }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @stock.destroy
        format.html { redirect_to exchange_stocks_path(exchange_id: @stock.exchange_id),
                      notice: 'Stock was successfully destroyed.' }
        format.json { render :show, status: :ok, location: exchange_stocks_path(exchange_id: @stock.exchange_id) }
      else
        format.html { render :show, alert: @stock.errors }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

private

  def stock_params
    params.require(:stock).permit(:name, :location, :exchange_id)
  end

  def set_stock
    @stock = Stock.find(params[:id])
  end

  def set_exchange
    @exchange = Exchange.find(params[:exchange_id])
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_for(stock) do |f| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%= f.text_field :name %>
  <%= f.hidden_field :exchange_id, value: @exchange.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', stock_path(@stock) %> |
<%= link_to 'Back', exchange_stocks_path(@exchange) %>

app/views/stocks/index.html.erb
<h1>Stocks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= link_to stock.name, exchange_stock_path(exchange_id: @exchange.id, id: stock.id) %></td>
        <td><%= link_to 'Edit', edit_exchange_stock_path(exchange_id: @exchange.id, id: stock.id) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_exchange_stock_path(exchange_id: @exchange.id) %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% stock_quotes = @stock.stock_quotes.paginate(page: params[:page], per_page: 50) %>
<h2><%= @stock.name %>'s Prices</h2>

<% if stock_quotes.count > 0 %>
  <%= will_paginate stock_quotes %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>

    <tbody>
      <% stock_quotes.each do |quote| %>
        <tr>
          <td><%= link_to "$#{quote.amount} @ #{quote.created_at}", quote %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h5> None </h5><br>
<% end %>
<br>

<%= link_to 'Edit', edit_exchange_stock_path(exchange_id: @exchange.id, id: @stock.id) %> |
<%= link_to 'Back', stocks_path %>