config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'exchanges#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api do
    namespace :v1 do
      resources :exchanges
      resources :stock_quotes, only: [:new, :show, :create, :edit, :update, :index]
      resources :transactions
      resources :sessions, only: [:create, :destroy]
    end
  end

  resources :exchanges do
    resources :stocks, only: [:new, :edit, :index, :show]
  end
  resources :stocks, only: [:destroy, :create, :update]
  resources :stock_quotes, only: [:show, :index]
  resources :transactions

  
end

app/models/stock_quote.rb
# StockQuote Schema
#
# id        integer
# amount    decimal
# stock_id  integer

# Commented out for now
# user_id   integer

class StockQuote < ApplicationRecord
  belongs_to :stock
  #belongs_to :user
end

app/controllers/api/v1/stock_quotes_controller.rb
class Api::V1::StockQuotesController < Api::V1::BaseController
  before_action :set_stock_quote, only: [:show, :edit, :update, :destroy]

  def index
    @stock_quotes = StockQuote.paginate(page: params[:page], per_page: 100)
  end

  def show
    render :show, status: :ok, location: @stock_quote
  end

  def new
    @stock_quote = StockQuote.new

    render :new, status: :ok, location: @stock_quote
  end

  def create
    stock_quote = StockQuote.new(stock_quote_params)

    if stock_quote.save
      render :show, status: :ok, location: stock_quote
    else
      render json: stock_quote.errors, status: :unprocessable_entity
    end
  end

private

  def stock_quote_params
    params.require(:stock_quote).permit(:amount, :stock_id)
  end

  def set_stock_quote
    @stock_quote = StockQuote.find(params[:id])
  end
end

app/controllers/stock_quotes_controller.rb
class StockQuotesController < ApplicationController
  before_action :set_stock_quote, only: [:show, :update, :destroy]

  def index
    @stock_quotes = StockQuote.paginate(page: params[:page], per_page: 100)
  end

  def show
    respond_to do |format|
      format.html { render 'show' }
      format.json { render :show, status: :ok, location: @stock_quote }
    end
  end

private

  def stock_quote_params
    params.require(:stock_quote).permit(:amount, :stock_id)
  end

  def set_stock_quote
    @stock_quote = StockQuote.find(params[:id])
  end
end

app/helpers/stock_quotes_helper.rb
module StockQuotesHelper
end

app/views/stock_quotes/index.html.erb
<h1>Stock Quotes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Quote</th>
    </tr>
  </thead>

  <tbody>
    <% @stock_quotes.each do |stock_quote| %>
      <tr>
        <td><%= link_to "#{stock_quote.amount} @ #{stock_quote.created_at}", stock_quote %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stock_quotes/show.html.erb
<h2>Transaction Information</h2><br>

<table class="table">
  <thead>
    <tr>
      <th>Quote</th>
      <th>Quoted On</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>$<%= @stock_quote.amount %>
      <td><%= @stock_quote.created_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back', stock_quotes_path %>